[package]
name = "serde-amf3"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.140" }

[dev-dependencies]
serde_json = "1.0.82"
serde = { version = "1.0.140", features = ["derive"] }
clap = { version = "3.2.13", features = ["derive"] }
